# Generated by Django 3.2.5 on 2021-07-12 19:35

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permisos', '0002_permisos_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('ciudad_id', models.AutoField(db_column='ciudad_id', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('configuracion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_per_page', models.IntegerField()),
                ('cant_lista_cobranza', models.IntegerField()),
                ('usar_fecha_servidor', models.CharField(default='si', max_length=20)),
                ('fecha_sistema', utils.custome_db_types.DateFieldCustome(blank=True, null=True)),
                ('costo_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidad_minima_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expensas_monto_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodo_ini', models.CharField(default='202101', max_length=20)),
                ('periodo_fin', models.CharField(default='202112', max_length=20)),
            ],
            options={
                'db_table': 'configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('pais_id', models.IntegerField(db_column='pais_id', primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='TiposMonedas',
            fields=[
                ('tipo_moneda_id', models.IntegerField(db_column='tipo_moneda_id', primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'tipos_monedas',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('sucursal_id', models.AutoField(db_column='sucursal_id', primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=250)),
                ('telefonos', models.CharField(max_length=250)),
                ('actividad', models.CharField(max_length=250)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('ciudad_id', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.ciudades')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('punto_id', models.AutoField(db_column='punto_id', primary_key=True, serialize=False)),
                ('punto', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('impresora_reportes', models.CharField(max_length=250)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('sucursal_id', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.sucursales')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'puntos',
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('moneda_id', models.IntegerField(db_column='moneda_id', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('tipo_moneda_id', models.ForeignKey(db_column='tipo_moneda_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tiposmonedas')),
            ],
            options={
                'db_table': 'monedas',
            },
        ),
        migrations.CreateModel(
            name='CobrosMensuales',
            fields=[
                ('cobro_mensual_id', models.AutoField(db_column='cobro_mensual_id', primary_key=True, serialize=False)),
                ('cobro_mensual', models.CharField(default='', max_length=150)),
                ('codigo', models.CharField(default='', max_length=20)),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_cobrar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'cobros_mensuales',
            },
        ),
        migrations.CreateModel(
            name='CobrosManuales',
            fields=[
                ('cobro_manual_id', models.AutoField(db_column='cobro_manual_id', primary_key=True, serialize=False)),
                ('cobro_manual', models.CharField(default='', max_length=150)),
                ('codigo', models.CharField(default='', max_length=20)),
                ('monto_porcentaje', models.CharField(default='', max_length=20)),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cobro_mensual_id', models.IntegerField(db_column='cobro_mensual_id')),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'cobros_manuales',
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='pais_id',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.paises'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='user_perfil_id',
            field=models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles'),
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('caja_id', models.AutoField(db_column='caja_id', primary_key=True, serialize=False)),
                ('caja', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('tipo_moneda_id', models.ForeignKey(db_column='tipo_moneda_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tiposmonedas')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'cajas',
            },
        ),
    ]
