# Generated by Django 3.2.5 on 2021-07-29 11:04

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('actividad_id', models.AutoField(db_column='actividad_id', primary_key=True, serialize=False)),
                ('actividad', models.CharField(default='', max_length=150)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('color_hex', models.CharField(default='', max_length=50)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('calendario_id', models.AutoField(db_column='calendario_id', primary_key=True, serialize=False)),
                ('fecha_actividad_ini', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_actividad_fin', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('departamento_id', models.IntegerField(default=0)),
                ('user_perfil_id_reserva', models.IntegerField(default=0)),
                ('fecha_reserva', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('detalle', models.CharField(max_length=250)),
                ('observacion', models.CharField(max_length=250)),
                ('user_perfil_id_confirma', models.IntegerField(default=0)),
                ('fecha_confirma', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_anula', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('actividad_id', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.PROTECT, to='calendario.actividades')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'calendario',
            },
        ),
    ]
