# Generated by Django 3.2.5 on 2021-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
