# Generated by Django 3.2.5 on 2021-07-12 20:20

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloques',
            fields=[
                ('bloque_id', models.AutoField(db_column='bloque_id', primary_key=True, serialize=False)),
                ('bloque', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=250)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'bloques',
            },
        ),
        migrations.CreateModel(
            name='Pisos',
            fields=[
                ('piso_id', models.AutoField(db_column='piso_id', primary_key=True, serialize=False)),
                ('piso', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'pisos',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamento_id', models.AutoField(db_column='departamento_id', primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20)),
                ('propietario_apellidos', models.CharField(max_length=150)),
                ('propietario_nombres', models.CharField(max_length=150)),
                ('propietario_ci_nit', models.CharField(max_length=50)),
                ('propietario_fonos', models.CharField(max_length=150)),
                ('propietario_email', models.CharField(max_length=150)),
                ('copropietario_apellidos', models.CharField(max_length=150)),
                ('copropietario_nombres', models.CharField(max_length=150)),
                ('copropietario_ci_nit', models.CharField(max_length=50)),
                ('copropietario_fonos', models.CharField(max_length=150)),
                ('copropietario_email', models.CharField(max_length=150)),
                ('metros2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('bloque_id', models.ForeignKey(db_column='bloque_id', on_delete=django.db.models.deletion.PROTECT, to='departamentos.bloques')),
                ('piso_id', models.ForeignKey(db_column='piso_id', on_delete=django.db.models.deletion.PROTECT, to='departamentos.pisos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
    ]
